#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# Start programs
$HOME/.screenlayout/monitor.sh &  # One monitor only
xsetroot -cursor_name left_ptr &
nitrogen --restore &
picom -f &
$HOME/.config/polybar/launch.sh

#bspc monitor HDMI1 -d I II 
bspc monitor DP1 -d I II III IV V VI

bspc config border_width        0 
bspc config window_gap          10 

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# To check and enable one by one

#bspc config focused_border_color      "#fbe319"
#bspc config active_border_color       "#fb19b0"
#bspc config normal_border_color       "#aa94a3"

#bspc config automatic_scheme           sprial
#bspc config history_aware_focus        true
#bspc config remove_disabled_monitors   true
#bspc config focus_follows_pointer      true
#bspc config remove_unplugged_monitors  true
#bspc config border_width               3
#bspc config window_gap                 10
#bspc config border_radius	   	8
#bspc config split_ratio                0.55
#bspc config borderless_monocle         true
#bspc config gapless_monocle            true









#bspc rule -a Gimp desktop='^8' state=floating follow=on

bspc rule -a firefox desktop='^3' follow=on
bspc rule -a Chromium desktop='^3' follow=on
bspc rule -a org.remmina.Remmina desktop='^2' follow=on
bspc rule -a code-oss desktop='^4' follow=on
bspc rule -a Spotify desktop='^5' follow=on
bspc rule -a Virt-manager desktop='^6' follow=on
bspc rule -a Pcmanfm desktop ='^3' state=floating follow=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# My custom floating apps

bspc rule -a thunar state=floating follow=on
