#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

$HOME/.screenlayout/monitors.sh &
xsetroot -cursor_name left_ptr &
nitrogen --restore &
picom -f &
$HOME/.config/polybar/launch.sh

bspc monitor HDMI1 -d I II 
bspc monitor DP1 -d III IV V VI

bspc config border_width        1 
bspc config window_gap          2 

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on

bspc rule -a firefox desktop='^1' follow=on
bspc rule -a Chromium desktop='^1' follow=on
bspc rule -a org.remmina.Remmina desktop='^2' follow=on
bspc rule -a code-oss desktop='^4' follow=on
bspc rule -a Spotify desktop='^5' follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
